/**
 * Gift-card catalog transcribed from card.pdf (24 pages, source rows 1-100).
 *
 * The source repeats Lane Bryant at rows 28 and 98, so the storefront exposes
 * 99 unique brands while retaining both source row numbers for traceability.
 * Amount ranges and fixed denominations are displayed as catalog information;
 * they are intentionally not treated as the storefront's sale price.
 */

export const giftCardCategories = [
  { slug: 'fashion-apparel', zhCN: '服饰鞋包', zhTW: '服飾鞋包', enUS: 'Fashion & Apparel', sortOrder: 90 },
  { slug: 'food-dining', zhCN: '餐饮美食', zhTW: '餐飲美食', enUS: 'Food & Dining', sortOrder: 80 },
  { slug: 'sports-outdoors', zhCN: '运动户外', zhTW: '運動戶外', enUS: 'Sports & Outdoors', sortOrder: 70 },
  { slug: 'home-lifestyle', zhCN: '家居生活', zhTW: '家居生活', enUS: 'Home & Lifestyle', sortOrder: 60 },
  { slug: 'technology-entertainment', zhCN: '数码娱乐', zhTW: '數位娛樂', enUS: 'Technology & Entertainment', sortOrder: 50 },
  { slug: 'travel-experiences', zhCN: '旅行体验', zhTW: '旅行體驗', enUS: 'Travel & Experiences', sortOrder: 40 },
  { slug: 'health-beauty-jewelry', zhCN: '健康美妆珠宝', zhTW: '健康美妝珠寶', enUS: 'Health, Beauty & Jewelry', sortOrder: 30 },
  { slug: 'pets-family', zhCN: '宠物亲子', zhTW: '寵物親子', enUS: 'Pets & Family', sortOrder: 20 },
  { slug: 'marketplaces-retail', zhCN: '综合零售', zhTW: '綜合零售', enUS: 'Marketplaces & Retail', sortOrder: 10 },
]

const catalogRows = [
  [1, 'Callaway', 'sports-outdoors', '$25/50/100/250'],
  [2, 'Gatorade', 'sports-outdoors', '$5.00 – $250.00'],
  [3, "Lands' End", 'fashion-apparel', '$5.00 – $500.00'],
  [4, 'Build-A-Bear Workshop', 'pets-family', '$5.00 – $500.00'],
  [5, '1-800 Baskets', 'food-dining', '$5.00 – $200.00'],
  [6, 'Home Chef', 'food-dining', '$50.00 – $250.00'],
  [7, 'Fruit Bouquets', 'food-dining', '$5.00 – $200.00'],
  [8, "Shari's Berries", 'food-dining', '$5.00 – $200.00'],
  [9, 'JTV', 'health-beauty-jewelry', '$15.00 – $500.00'],
  [10, "Macy's", 'marketplaces-retail', '$5.00 – $500.00'],
  [11, 'Under Armour', 'sports-outdoors', '$5.00 – $500.00'],
  [12, 'adidas', 'sports-outdoors', '$5.00 – $500.00'],
  [13, 'Petco', 'pets-family', '$10.00 – $200.00'],
  [14, 'Rent The Runway', 'fashion-apparel', '$25.00 – $500.00'],
  [15, 'Sunglass Hut', 'fashion-apparel', '$10.00 – $200.00'],
  [16, 'Finish Line', 'sports-outdoors', '$5.00 – $250.00'],
  [17, '1-800flowers.com', 'food-dining', '$10/25/50'],
  [18, 'Harry & David', 'food-dining', '$15.00 – $500.00'],
  [19, 'The Popcorn Factory', 'food-dining', '$15.00 – $500.00'],
  [20, 'Shutterfly, Inc.', 'home-lifestyle', '$25/50'],
  [21, 'LOFT', 'fashion-apparel', '$5.00 – $500.00'],
  [22, 'KAY Jewelers', 'health-beauty-jewelry', '$25.00 – $500.00'],
  [23, "Tilly's", 'fashion-apparel', '$15.00 – $500.00'],
  [24, 'Office Depot OfficeMax', 'marketplaces-retail', '$5.00 – $200.00'],
  [25, 'Pacific Sunwear', 'fashion-apparel', '$10.00 – $200.00'],
  [26, 'Columbia Sportswear', 'sports-outdoors', '$10.00 – $250.00'],
  [27, 'Famous Footwear', 'fashion-apparel', '$10.00 – $250.00'],
  [[28, 98], 'Lane Bryant', 'fashion-apparel', '$15.00 – $200.00'],
  [29, 'Advance Auto Parts', 'marketplaces-retail', '$10/25/50/100'],
  [30, 'Belk', 'marketplaces-retail', '$25/50'],
  [31, 'maurices', 'fashion-apparel', '$5.00 – $500.00'],
  [32, 'Ann Taylor', 'fashion-apparel', '$5.00 – $500.00'],
  [33, 'Athleta', 'sports-outdoors', '$10.00 – $500.00'],
  [34, 'Gap', 'fashion-apparel', '$10.00 – $500.00'],
  [35, 'Banana Republic', 'fashion-apparel', '$10.00 – $500.00'],
  [36, 'Old Navy', 'fashion-apparel', '$10.00 – $500.00'],
  [37, 'Bowlero', 'travel-experiences', '$25.00 – $500.00'],
  [38, 'The Container Store', 'home-lifestyle', '$5.00 – $100.00'],
  [39, 'Tommy John', 'fashion-apparel', '$25.00 – $500.00'],
  [40, 'Paramount+', 'technology-entertainment', '$25/50/100'],
  [41, 'ZWILLING', 'home-lifestyle', '$25.00 – $500.00'],
  [42, 'Yankee Candle', 'home-lifestyle', '$5.00 – $250.00'],
  [43, 'JCPenney', 'marketplaces-retail', '$10/25/50/100'],
  [44, 'Hanna Andersson', 'fashion-apparel', '$25.00 – $500.00'],
  [45, 'Nautica', 'fashion-apparel', '$5.00 – $500.00'],
  [46, "Carter's / OshKosh B'gosh", 'pets-family', '$10.00 – $500.00'],
  [47, "Peet's Coffee", 'food-dining', '$10.00 – $200.00'],
  [48, 'GUESS', 'fashion-apparel', '$15.00 – $500.00'],
  [49, 'Lucky Brand', 'fashion-apparel', '$5.00 – $500.00'],
  [50, 'Fanatics', 'sports-outdoors', '$25/50/100'],
  [51, 'Kendra Scott', 'health-beauty-jewelry', '$5.00 – $500.00'],
  [52, 'Tommy Bahama', 'fashion-apparel', '$15.00 – $500.00'],
  [53, 'Kobo', 'technology-entertainment', '$10.00 – $250.00'],
  [54, 'The Vitamin Shoppe', 'health-beauty-jewelry', '$5.00 – $250.00'],
  [55, 'ThirdLove', 'fashion-apparel', '$25.00 – $500.00'],
  [56, "Boscov's", 'marketplaces-retail', '$15.00 – $250.00'],
  [57, 'Apple', 'technology-entertainment', '$5.00 – $500.00'],
  [58, 'H&M', 'fashion-apparel', '$5.00 – $300.00'],
  [59, 'Chubbies', 'fashion-apparel', '$25.00 – $500.00'],
  [60, 'Holland America Line', 'travel-experiences', '$25.00 – $2,000.00'],
  [61, 'REI Co-op', 'sports-outdoors', '$15.00 – $500.00'],
  [62, 'Hollister', 'fashion-apparel', '$5.00 – $500.00'],
  [63, 'J.Crew', 'fashion-apparel', '$20.00 – $500.00'],
  [64, "Lulu's", 'fashion-apparel', '$15.00 – $200.00'],
  [65, 'Bed Bath & Beyond', 'home-lifestyle', '$5.00 – $500.00'],
  [66, 'Hibbett Sports', 'sports-outdoors', '$25.00 – $250.00'],
  [67, 'Aeropostale', 'fashion-apparel', '$5.00 – $500.00'],
  [68, "Chico's", 'fashion-apparel', '$10.00 – $500.00'],
  [69, 'White House Black Market', 'fashion-apparel', '$10.00 – $500.00'],
  [70, 'Groupon', 'travel-experiences', '$10.00 – $200.00'],
  [71, 'eBay', 'marketplaces-retail', '$5.00 – $200.00'],
  [72, 'Zappos.com', 'fashion-apparel', '$10/15/100'],
  [73, 'Staples', 'marketplaces-retail', '$5.00 – $500.00'],
  [74, 'StubHub', 'travel-experiences', '$25.00 – $500.00'],
  [75, 'Marriott Hotels', 'travel-experiences', '$25.00 – $2,000.00'],
  [76, 'SeaWorld', 'travel-experiences', '$25.00 – $250.00'],
  [77, 'Atlantis Bahamas Resort', 'travel-experiences', '$5.00 – $2,000.00'],
  [78, 'Bath & Body Works', 'health-beauty-jewelry', '$5.00 – $500.00'],
  [79, 'GNC', 'health-beauty-jewelry', '$5.00 – $500.00'],
  [80, 'Allbirds', 'fashion-apparel', '$25.00 – $250.00'],
  [81, 'American Eagle Outfitters', 'fashion-apparel', '$5.00 – $500.00'],
  [82, 'Sling TV', 'technology-entertainment', '$25.00 – $100.00'],
  [83, 'Best Western', 'travel-experiences', '$25.00 – $500.00'],
  [84, 'Skechers', 'fashion-apparel', '$15.00 – $500.00'],
  [85, 'Meta Quest', 'technology-entertainment', '$15/25/50'],
  [86, 'Chewy', 'pets-family', '$5.00 – $500.00'],
  [87, 'Tractor Supply Co.', 'marketplaces-retail', '$15.00 – $250.00'],
  [88, 'IKEA', 'home-lifestyle', '$25.00 – $500.00'],
  [89, 'Etsy', 'marketplaces-retail', '$15.00 – $500.00'],
  [90, 'Academy Sports & Outdoors', 'sports-outdoors', '$5.00 – $1,500.00'],
  [91, "Applebee's", 'food-dining', '$5.00 – $200.00'],
  [92, 'Five Guys', 'food-dining', '$10.00 – $200.00'],
  [93, 'Cotton On Body', 'fashion-apparel', '$20.00 – $200.00'],
  [94, 'Grown Brilliance', 'health-beauty-jewelry', '$25.00 – $2,000.00'],
  [95, 'Princess Cruise Lines', 'travel-experiences', '$25.00 – $2,000.00'],
  [96, 'Solo Stove', 'home-lifestyle', '$25.00 – $500.00'],
  [97, 'Shipt', 'food-dining', '$99'],
  [99, 'True Classic', 'fashion-apparel', '$5.00 – $500.00'],
  [100, 'Factor', 'food-dining', '$95/115/140/155'],
]

// Concise English introductions transcribed and lightly cleaned from card.pdf.
// UI labels, denomination text and OCR artifacts are intentionally excluded.
const catalogDescriptions = {
  'Callaway': 'Fuel a golfer’s passion with a Callaway gift card from one of the most recognized and respected names in golf.',
  'Gatorade': 'Gatorade is an American sports beverage and food brand known for its signature sports drinks and distributed in more than 80 countries.',
  "Lands' End": 'Lands’ End is a classic American lifestyle brand known for quality, legendary service and lasting value across clothing and home products.',
  'Build-A-Bear Workshop': 'Build-A-Bear lets guests create and personalize a furry friend with clothing, sounds, scents and accessories for a memorable experience.',
  '1-800 Baskets': '1-800 Baskets creates carefully designed food and gift baskets for birthdays, celebrations, sympathy, thank-you gifts and many other occasions.',
  'Home Chef': 'Home Chef is a nationwide meal-kit service that delivers fresh, pre-portioned ingredients to customers each week.',
  'Fruit Bouquets': 'Fruit Bouquets offers fresh fruit arrangements, including hand-crafted chocolate-dipped fruit, delivered for celebrations and everyday treats.',
  "Shari's Berries": 'Shari’s Berries is known for imaginative gourmet gifts and farm-fresh strawberries dipped in indulgent toppings for every occasion.',
  'JTV': 'JTV is a jewelry and gemstone retailer offering live shopping, online collections and exclusive styles at accessible prices.',
  "Macy's": 'Macy’s is an iconic American department store offering fashion, beauty, home, jewelry and more from leading brands and designers.',
  'Under Armour': 'Under Armour creates technical performance apparel, footwear and accessories designed to help athletes train, perform and recover.',
  'adidas': 'adidas combines innovative performance technology with streetwear inspired by decades of athletic heritage.',
  'Petco': 'Petco is a leading pet specialty retailer offering products, services and advice for dogs, cats, fish, birds, reptiles and small animals.',
  'Rent The Runway': 'Rent the Runway provides access to designer apparel and accessories through rental, resale and fashion subscription services.',
  'Sunglass Hut': 'Sunglass Hut offers fashion and performance sunglasses from leading designer brands including Ray-Ban, Prada and Oakley.',
  'Finish Line': 'Finish Line is an athletic retailer offering brand-name footwear, apparel and accessories in stores and online.',
  '1-800flowers.com': '1-800flowers.com and its family of brands offer flowers, gift baskets and specialty items for celebrations and thoughtful moments.',
  'Harry & David': 'Harry & David has crafted premium gourmet gifts, from Royal Riviera pears to chocolates and specialty foods, since 1934.',
  'The Popcorn Factory': 'The Popcorn Factory creates giftable popcorn in butter, cheddar, caramel, chocolate and other memorable flavors.',
  'Shutterfly, Inc.': 'Shutterfly helps turn favorite photos into photo books, cards, stationery, prints, calendars and personalized gifts.',
  'LOFT': 'LOFT creates modern, feminine and versatile clothing designed to help women look and feel confident throughout the day.',
  'KAY Jewelers': 'KAY Jewelers offers timeless and distinctive jewelry for meaningful moments, relationships and celebrations across a range of budgets.',
  "Tilly's": 'Tilly’s carries sought-after brands rooted in action sports, music, art, youth culture and fashion.',
  'Office Depot OfficeMax': 'Office Depot OfficeMax offers office supplies, paper, technology, furniture and everyday business essentials online and in stores.',
  'Pacific Sunwear': 'PacSun blends streetwear, emerging brands and fashion essentials inspired by California youth culture and creative freedom.',
  'Columbia Sportswear': 'Columbia has created innovative outdoor apparel, footwear and equipment designed to keep people warm, dry, cool and protected since 1938.',
  'Famous Footwear': 'Famous Footwear offers well-known footwear brands and an easy shopping experience for the whole family.',
  'Lane Bryant': 'Lane Bryant offers stylish, high-quality women’s apparel, activewear, accessories and Cacique intimates in inclusive sizes.',
  'Advance Auto Parts': 'Advance Auto Parts provides automotive parts and complete car-care essentials for do-it-yourself customers.',
  'Belk': 'Belk offers modern Southern style across fashion, beauty and home through stores across the southeastern United States.',
  'maurices': 'maurices offers affordable, versatile women’s fashion with warm service and a strong commitment to local communities.',
  'Ann Taylor': 'Ann Taylor is a modern style destination designed to give women inspiration and confidence for every part of their day.',
  'Athleta': 'Athleta designs performance apparel and gear for active women, balancing functional advantages with confident style.',
  'Gap': 'Gap offers wardrobe essentials, denim, clothing and accessories for women, men, children and babies.',
  'Banana Republic': 'Banana Republic is known for exceptional quality, luxurious fabrics and refined tailoring for work and casual occasions.',
  'Old Navy': 'Old Navy offers affordable fashion, denim, graphic tees and everyday style for the entire family.',
  'Bowlero': 'Bowlero and AMF centers combine bowling, arcade games, signature food and drinks for parties and all-ages entertainment.',
  'The Container Store': 'The Container Store specializes in storage and organization solutions for closets, kitchens, children’s rooms and every space in between.',
  'Tommy John': 'Tommy John makes premium underwear and essentials with soft fabrics and innovative features designed for everyday comfort.',
  'Paramount+': 'Paramount+ streams movies, originals, live sports and favorites from CBS, Nickelodeon, Comedy Central, BET, MTV and more.',
  'ZWILLING': 'ZWILLING offers premium kitchenware and thoughtful products for birthdays, holidays, thank-you gifts and everyday occasions.',
  'Yankee Candle': 'Yankee Candle is known for premium scented candles in an extensive range of classic, seasonal and new fragrances.',
  'JCPenney': 'JCPenney offers family apparel, home furnishings, fine jewelry, footwear, accessories, beauty products and services at smart prices.',
  'Hanna Andersson': 'Hanna Andersson creates durable children’s clothing with Scandinavian-inspired design, organic cotton and sustainability-focused quality.',
  'Nautica': 'Nautica is a globally recognized, nautical-inspired American lifestyle brand for men, women, children and the home.',
  "Carter's / OshKosh B'gosh": 'Carter’s and OshKosh B’gosh offer trusted children’s clothing, sleepwear, gifts and accessories from newborn through size 12.',
  "Peet's Coffee": 'Peet’s Coffee sources high-quality beans and hand-roasts them in small batches according to standards established in 1966.',
  'GUESS': 'GUESS is a global lifestyle brand designing and distributing denim, apparel and accessories for women, men and children.',
  'Lucky Brand': 'Lucky Brand is known for vintage-inspired apparel, premium denim and a relaxed bohemian style.',
  'Fanatics': 'Fanatics offers a large collection of officially licensed fan gear from major leagues, teams and athletes.',
  'Kendra Scott': 'Kendra Scott creates accessible luxury jewelry inspired by colorful design and the values of family, fashion and philanthropy.',
  'Tommy Bahama': 'Tommy Bahama brings an island state of mind to apparel, accessories, restaurants and relaxed lifestyle experiences.',
  'Kobo': 'Kobo gives readers access to millions of eBooks and audiobooks across Kobo devices and the free Kobo app.',
  'The Vitamin Shoppe': 'The Vitamin Shoppe offers trusted wellness, sports nutrition, energy and supplement products supported by knowledgeable health specialists.',
  'ThirdLove': 'ThirdLove designs comfortable, better-fitting bras, underwear, sleepwear and intimates across an extensive range of sizes.',
  "Boscov's": 'Boscov’s offers a broad selection of fashion, home and everyday products across more than 200 departments.',
  'Apple': 'The Apple Gift Card can be used for Apple products, accessories, apps, games, music, movies, subscriptions and other eligible US purchases.',
  'H&M': 'H&M offers affordable fashion, accessories, essentials, activewear and home products for women, men, teens and children.',
  'Chubbies': 'Chubbies creates comfortable men’s apparel and weekend-ready essentials built around a relaxed, community-focused spirit.',
  'Holland America Line': 'Holland America Line offers premium cruises, elegant mid-sized ships, worldwide itineraries, dining and onboard experiences.',
  'REI Co-op': 'REI Co-op offers outdoor gear, clothing and experiences that help members and customers enjoy the outdoors.',
  'Hollister': 'Hollister brings effortless California-inspired style to jeans, tops, swimwear, shoes, outerwear and everyday essentials.',
  'J.Crew': 'J.Crew creates classic, colorful clothing using distinctive fabrics sourced from around the world for women, men and children.',
  "Lulu's": 'Lulus is a California-based women’s fashion brand offering chic, on-trend styles for occasions and everyday confidence.',
  'Bed Bath & Beyond': 'Bed Bath & Beyond offers furniture, décor, rugs, designer brands and home essentials online and through its app.',
  'Hibbett Sports': 'Hibbett Sports is a sporting goods retailer specializing in team-sports equipment, footwear and apparel.',
  'Aeropostale': 'Aéropostale is a modern casual-fashion retailer offering denim, tees, hoodies, active basics and trend-led styles.',
  "Chico's": 'Chico’s offers distinctive women’s clothing and accessories with figure-flattering design, relaxed comfort and personalized service.',
  'White House Black Market': 'White House Black Market offers versatile modern womenswear, everyday luxury and complimentary expert styling advice.',
  'Groupon': 'Groupon helps customers discover restaurants, wellness experiences, activities and local offers at discounted prices.',
  'eBay': 'eBay connects shoppers with billions of new and pre-owned listings from sellers around the world.',
  'Zappos.com': 'Zappos offers shoes, clothing, handbags and accessories from established and emerging brands with customer-focused service.',
  'Staples': 'Staples offers laptops, tablets, furniture, luggage and business essentials in stores and online.',
  'StubHub': 'StubHub is a global ticket marketplace for sporting events, concerts, theater and other live entertainment.',
  'Marriott Hotels': 'Marriott offers stays and experiences across more than 30 hotel brands, including dining, spas and golf at participating properties.',
  'SeaWorld': 'SeaWorld and its sister parks offer animal encounters, thrilling rides, live shows and family experiences across the United States.',
  'Atlantis Bahamas Resort': 'Atlantis Bahamas is an ocean-themed Paradise Island resort with accommodations, a water park, marine exhibits, dining and activities for all ages.',
  'Bath & Body Works': 'Bath & Body Works offers fragrances, body care, home scents, soaps, sanitizers and giftable personal-care products.',
  'GNC': 'GNC provides nutrition, wellness and performance products designed to motivate and support healthier living.',
  'Allbirds': 'Allbirds combines comfort, simple style and durability with materials and practices focused on sustainability.',
  'American Eagle Outfitters': 'American Eagle offers jeans, casual fashion and everyday essentials designed to celebrate individual style.',
  'Sling TV': 'Sling TV is a customizable live-television streaming service that lets viewers personalize their channel lineup.',
  'Best Western': 'Best Western gift cards can be used at participating BWH Hotels around the world and do not expire.',
  'Skechers': 'Skechers offers lifestyle, performance and work footwear, plus apparel and accessories for men, women and children.',
  'Meta Quest': 'Meta Quest opens access to mixed-reality games, creative experiences, social connection and live events in the Meta Horizon Store.',
  'Chewy': 'Chewy offers pet essentials from leading brands, convenient delivery, expert advice, pharmacy services and round-the-clock customer support.',
  'Tractor Supply Co.': 'Tractor Supply serves farmers, ranchers, gardeners, pet owners and rural-lifestyle customers with practical products and expertise.',
  'IKEA': 'IKEA offers thousands of affordable home-furnishing ideas and products online and in stores.',
  'Etsy': 'Etsy connects shoppers with distinctive products from independent sellers and supports a global community of small businesses.',
  'Academy Sports & Outdoors': 'Academy is a sporting-goods and outdoor-recreation retailer offering national brands and private-label products across key activity categories.',
  "Applebee's": 'Applebee’s gift cards can be used for casual dining at participating restaurants across the United States and Canada.',
  'Five Guys': 'Five Guys is a family-run burgers-and-fries restaurant focused on freshly prepared, craveable food.',
  'Cotton On Body': 'Cotton On Body is a women-led global fashion brand offering activewear, intimates, loungewear and swimwear.',
  'Grown Brilliance': 'Grown Brilliance creates conflict-free lab-grown diamond jewelry in timeless, contemporary and customizable designs.',
  'Princess Cruise Lines': 'Princess Cruises offers worldwide voyages aboard modern ships with extensive onboard options and attentive customer service.',
  'Solo Stove': 'Solo Stove uses innovative airflow technology to create smokeless fire pits and outdoor products designed for efficient, enjoyable gatherings.',
  'Shipt': 'Shipt is a membership-based online marketplace delivering groceries and household essentials through a convenient app and shopper community.',
  'True Classic': 'True Classic makes ultra-soft, carefully fitted men’s tees, denim, polos, button-ups, outerwear and timeless everyday basics.',
  'Factor': 'Factor delivers healthy, chef-prepared meals that are ready to heat and eat with minimal preparation.',
}

const slugify = (value) => value
  .normalize('NFKD')
  .replace(/[\u0300-\u036f]/g, '')
  .replace(/&/g, ' and ')
  .replace(/\+/g, ' plus ')
  .replace(/[^a-zA-Z0-9]+/g, '-')
  .replace(/^-|-$/g, '')
  .toLowerCase()

export const giftCardCatalog = catalogRows.map(([source, brand, category, availableAmounts]) => ({
  sourceNumbers: Array.isArray(source) ? source : [source],
  brand,
  category,
  availableAmounts,
  description: catalogDescriptions[brand],
  slug: brand === 'Apple' ? 'apple-gift-card-us-25' : `${slugify(brand)}-gift-card`,
}))
